---
name: Test building on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Test with ${{ matrix.compiler }} and ${{ matrix.dependencies }} dependencies"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        compiler: ['gcc', 'clang']
        dependencies: ['internal', 'external']

    steps:
      - name: Prepare ${{ matrix.compiler }} build environment
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            ${{ matrix.compiler }} \
            gettext \
            libpurple-dev \
            ninja-build \
            python3-pip
          pip3 install --break-system-packages meson

      - name: Install external dependencies
        if: matrix.dependencies == 'external'
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            libgadu-dev \
            libmeanwhile-dev

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Setup Meson build
        run: CC=${{ matrix.compiler }} meson setup build

      - name: Build project
        run: ninja -C build turtles

      - name: Install build results
        run: DESTDIR=$PWD/dist ninja -C build install

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        if: ${{ !env.ACT }}
        with:
          name: "Linux ${{ matrix.compiler }} with ${{ matrix.dependencies }} dependencies"
          path: ./dist
