on:
  push:
    branches:
      - main

name: "Upload pot file to Transifex"

jobs:
  retro-prpl-pot:
    name: upload new pot file
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Prepare build environment
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            build-essential \
            codespell \
            gettext \
            libpurple-dev \
            meson
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Setup Meson build
        run: meson setup build

      - name: Build project
        run: ninja -C build retro-prpl-pot

      - name: Upload pot file
        uses: transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189  # v2
        with:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
